#!/bin/bash

# Function to generate a random name
generate_random_name() {
  echo "$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)"
}

# Update package list and install required packages
sudo apt-get update
sudo apt-get install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev screen

# Clone xmrig repository
git clone https://github.com/xmrig/xmrig.git

# Create build directory and navigate into it
mkdir xmrig/build && cd xmrig/build

# Run cmake to configure the build
cmake ..

# Use make to build the xmrig executable using available CPU cores
make -j$(nproc)

# Generate a random name
random_name=$(generate_random_name)

# Create a screen session and run xmrig with the specified parameters
screen -dmS xmrig_session ./xmrig --coin XMR --url "xmr.kryptex.network:7777" --user "45PCz5esnjFjn4RamcpL3QHoGpQoSjs867eG1tvfyrVxeNB3fdgmNYGhquf8mMVmCiiWscKFodCVvcHQDHSDRA3u294f9SL/$random_name"

echo "xmrig is running in a screen session with name 'xmrig_session'. Use 'screen -r xmrig_session' to attach to the session."
echo "Generated random name: $random_name"
